import { cleanSongTitle, cleanPlaylistTitles } from '../../../src/lib/titleCleaner.js';
const p = (t, c, o={}) => { const r = cleanSongTitle(t, c, o); console.log(JSON.stringify(t), '|', c, '=>', JSON.stringify({title:r.title, alt:r.altTitle, artist:r.artist, aft:r.artistFromTitle, q:r.cleanQuery})); };
const yt = {source:'youtube'};
p('Nightcore - Angel With A Shotgun','NightcoreReality',yt);
p('Nightcore ~ Hikaru Nara','Nightcore Anime',yt);
p('Lunatic Eyes ~ Invisible Full Moon','ZUN',yt);
p('ZUN - Lunatic Eyes ~ Invisible Full Moon','x',yt);
p('Artist - Song ~ Night Ver.','Chan',yt);
p('Artist - ~Song~','Chan',yt);
p('Artist - Song ~','Chan',yt);
p('Artist - A ~ B ~ C','Chan',yt);
p('Artist - Song (Remix) ~ Night Ver.','Chan',yt);
p('Aimer - Ref:rain ~ piano ver.','Chan',yt);
const pl1 = ['Nightcore - Faded','Monster [Nightcore]','Nightcore ~ Hikaru Nara'];
const c1 = cleanPlaylistTitles(pl1);
for (const t of pl1) p(t,'NCChan',{...yt, playlistTitles:c1});
const pl2 = ['Camellia - GHOST','xi - Blue Zenith (Camellia)','Camellia - Exit This Earth\'s Atomosphere'];
const c2 = cleanPlaylistTitles(pl2);
for (const t of pl2) p(t,'Chan',{...yt, playlistTitles:c2});
const pl3 = ['Rammstein - Du Hast (HD)','Rammstein - Sonne (HD)'];
const c3 = cleanPlaylistTitles(pl3);
for (const t of pl3) p(t,'RammsteinOfficial',{...yt, playlistTitles:c3});
p('Shape of You - Stormzy Remix','Ed Sheeran',{source:'spotify',providerArtist:'Ed Sheeran'});
