import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const OUT = path.dirname(fileURLToPath(import.meta.url));
const URL_ = 'https://music.youtube.com/playlist?list=PLJU2iuLr5pzzwD1BjsQSX4Exb-w1Wc2Kp';
const kill = setTimeout(() => { console.error('HARD TIMEOUT'); process.exit(2); }, 100000);
const browser = await chromium.launch({ args: ['--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const r = { api: [], osuSearchCalls: 0 };
page.on('request', (q) => { if (q.url().includes('/api/osu/search')) r.osuSearchCalls++; });
page.on('response', async (res) => {
  if (res.url().includes('/api/playlist')) { try { const d = await res.json(); r.api.push({ n: d.songs?.length, returnedCount: d.returnedCount, loadedCount: d.loadedCount, unavailableCount: d.unavailableCount, truncated: d.truncated, playlistLength: d.playlistLength }); } catch {} }
});
await page.goto('http://localhost:3000', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
await page.fill('#playlist-url-input', URL_);
await page.press('#playlist-url-input', 'Enter');
const n = page.getByText(/Showing \d+ of \d+ songs\./).first();
await n.waitFor({ timeout: 45000 });
await page.waitForTimeout(2500);
r.desktopNotice = (await n.innerText()).trim();
r.desktopRows = await page.locator('[id^="checkbox-song-"]:visible').count();
r.desktopRowsAll = await page.locator('[id^="checkbox-song-"]').count();
await page.screenshot({ path: path.join(OUT, 'r1-desktop.png') });
await page.setViewportSize({ width: 375, height: 812 });
await page.waitForTimeout(800);
r.phoneNoticeVisible = await n.isVisible();
r.phoneNotice = (await n.innerText()).trim();
r.phoneRowsVisible = await page.locator('[id^="checkbox-song-"]:visible').count();
r.phoneScrollOk = await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth);
await n.scrollIntoViewIfNeeded();
await page.screenshot({ path: path.join(OUT, 'r1-phone.png') });
await page.screenshot({ path: path.join(OUT, 'r1-phone-full.png'), fullPage: true });
r.noticeDash = /[-–—]/.test(r.desktopNotice);
await page.setViewportSize({ width: 1280, height: 800 });
await page.fill('#playlist-url-input', URL_);
await page.press('#playlist-url-input', 'Enter');
const t = page.getByText(/unavailable on YouTube(?!\.)/).first();
await t.waitFor({ timeout: 45000 });
r.toast = (await t.innerText()).trim();
r.toastDash = /[-–—]/.test(r.toast);
r.rowsAfterAppend = await page.locator('[id^="checkbox-song-"]').count();
await page.screenshot({ path: path.join(OUT, 'r1-append.png') });
console.log(JSON.stringify(r, null, 2));
await browser.close(); clearTimeout(kill);
